eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/
server:
  port: 8003
spring:
  application:
    name: ribbon-client
management:
  security:
    enabled: false
logging:
  path: logs