server:
  port: 8768
spring:
  application:
    name: admin-service
  boot:
    admin:
      routes:
        # 指定从终端获取的信息接口
        endpoints: env, metrics, trace, dump, jolokia, info, logfile, refresh, flyway, liquibase, heapdump, loggers, auditevents, hystrix.stream
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
# 关闭安全认证
management:
  security:
    enabled: false
logging:
  path: logs