eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8000
spring:
  application:
    name: hi-service
management:
  security:
    enabled: false
logging:
  path: logs