spring:
  application:
    name: discovery-cluster

---
spring:
  profiles: discovery1
eureka:
  instance:
      hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:8762/eureka
server:
  port: 8761
---
spring:
  profiles: discovery2
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka
server:
  port: 8762